### ISSUE TITLE
Главная страница

### ISSUE THREAD

**Issue by dcversus** [uz0/hexcraft#10]
Лендинг с названием, логотипом, кнопкой "играть" и ссылками на новости, об игре и гитхаб.
Что-то в духе https://www.gitkraken.com/

Нужно также подобрать картинку на фон (для начала что-то на тему игры, потом будет скрин из самой игры)
- [x] скетч
- [ ] картинка для бекграунда

**Comment by olgakram** [comment]
![-](https://cloud.githubusercontent.com/assets/17432737/14228462/5e07028a-f91e-11e5-9269-3073f7e8e820.png)

**Comment by dcversus** [comment]
наверно на главной лучше без шапки и футера? а кнопки (новости, об игре и гитхаб) разместить под кнопкой "играть". А то сейчас лого и кнопка играть дублируются

**Comment by olgakram** [comment]
![2016-04-02](https://cloud.githubusercontent.com/assets/17432737/14228530/670520fa-f91f-11e5-88e9-302b5b1569e8.png)

**Comment by dcversus** [comment]
без футера, а ссылки под кнопкой играть
