### ISSUE TITLE
гостевой режим игры

### ISSUE THREAD

**Issue by dcversus** [uz0/hexcraft#109]
на экране кнопка "войти как гость", можно указать ник (не обязательно) создается новая учетка и сразу получает токен и входит в игру (без пароля)

**Comment by TwoAbove** [comment]
Может оставить моё решение, оно работает с существующей моделью, а время жизни токена только уменьшить?

**Comment by dcversus** [comment]
Твое решение не работает, использовать никнейм можно только единожды
