### ISSUE TITLE
Новости

### ISSUE THREAD

**Issue by dcversus** [uz0/hexcraft#12]
Типовая новость состоит из заголовка, даты, иконки и текста. Детальной страницы новости нету. Новость может не иметь текста (например автоматическая новость о новой сборке проекта). 

![image](https://cloud.githubusercontent.com/assets/8696354/14139451/d9c63a1c-f67b-11e5-8bc6-b06aeec8db25.png)

Возможно в стиле гитхаба (как на примере). 

В скетч нужно включить шапку с логотипом и ссылками: "играть", "об игре", "новости". И подвал сайта с ссылками на гитхаб и авторством.

**Comment by olgakram** [comment]
![-](https://cloud.githubusercontent.com/assets/17432737/14228459/4feb6a88-f91e-11e5-863c-0ca1e90deb20.png)

**Comment by dcversus** [comment]
А что делает панель справа? Не вижу смысла хранить признаки "новость или обновление" и соотв. фильтровать. Календарь... ну у нас не будет столько событий, даже пагинацию не предусматриваем (~60 записей всего будет)

**Comment by olgakram** [comment]
зачем нам просматривать всю историю обновлений, когда мы хотим посмотреть конкретно новости? сам сегодня говорил, что потом можно бдет разделить "новости" и "историю изменений", пока этого нет, есть фильтр.

**Comment by olgakram** [comment]
и тогда возникает вопрос о верхнем меню здесь. на главной нет, а тут есть...

**Comment by dcversus** [comment]
Главная - лендинг, а это внутренняя страница. Здесь есть футер и хедер, там нету. Фильтровать нет смысла, тк повторюсь, у нас мало автоматической информации и она будет проходить ручную модерацию. Не нужно перегружать интерфейс контролами, мы делаем прототип.

**Comment by efim1382** [comment]
можно в скетч включить для примера новость с картинкой?
