### ISSUE TITLE
Баллы

### ISSUE THREAD

**Issue by olgakram** [uz0/hexcraft#132]
Требуется уточнение
Отображать количество набранных баллов,хранить баллы, выводить список лидеров

**Comment by dcversus** [comment]
ну это явно на будущее) Мы по сути убрали регистрацию итп. Так что вопрос что и где хранить итп.

**Comment by olgakram** [comment]
в правилах написано "За каждый ход игрок получает 1 балл. За каждую захваченную фишку оппонента, игроку начисляется 2 балла. За победу в игре 10 баллов. Баллы игрока за все игры суммируются и формируют список лидеров"

**Comment by olgakram** [comment]
dв будущем нужно реализовать

**Comment by dcversus** [comment]
Угу, это нужно срочно поправить

**Comment by olgakram** [comment]
убрать текст или функционал добавить ?

**Comment by dcversus** [comment]
убрать текст!!111
