### ISSUE TITLE
правки по главной странице

### ISSUE THREAD

**Issue by dcversus** [uz0/hexcraft#17]
- [x] блок с кнопкой играть разместить внизу экрана (при любых размерах). Главная страница должна занимать весь экран и нижний блок должен быть "прижат" к нижней части экрана
- [x] размер блока с кнопкой играть нужно сделать больше (такой же размер как и блока с логотипом и текстом
- [x] блок с логотипом и текстом выровнять по вертикали
- [x] размер заголовка Hexcraft сделать крупнее
- [x] описание заменить на "логическая игра" и сделать крупнее
- [x] серый фон, который потом будет заменен на картинку сделать во весь экран
- [x] в мобильной версии разместить логотип выше описания с заголовком

![image](https://cloud.githubusercontent.com/assets/8696354/14324688/7e6dd036-fc2e-11e5-8d1a-42166cecfae1.png)

**Comment by efim1382** [comment]
С мобилки еще не тестировал

**Comment by danilstoyanov** [comment]
Доделал адаптивность на планшетах и мобильных устройствах
