### ISSUE TITLE
скетчи игровых экранов

### ISSUE THREAD

**Issue by dcversus** [uz0/hexcraft#19]
- [x] экран загрузки (не обязательно)
- [x] авторизация\вход (только ввод логина и пароля, если авторизован пропускаем)
- [x] экран выбора игры (список игр, список игроков, кнопки создания игры и выхода)
- [x] экран игры (требуется обсуждение)

**Comment by dcversus** [comment]
Детали в задаче #7

**Comment by olgakram** [comment]
регистрация по почте будет ?

**Comment by olgakram** [comment]
ее рисовать?

**Comment by olgakram** [comment]
у пользователя кстати что то типо личного кабинета будет?

**Comment by olgakram** [comment]
статистика игр, рейтинг, аватарка и.т.д

**Comment by dcversus** [comment]
личного кабинета не будет, только поле логина и пароля и кнопка войти
регистрации сейчас не будет, в следующей итерации

**Comment by olgakram** [comment]
регистрацию нарисовала.  думаю загрузку нужно все-таки к дизайну отнести, скетч для нее не нужен.

**Comment by olgakram** [comment]
у нас есть список игр, которые удут? не совсем понятно что под этим подразумевается

**Comment by olgakram** [comment]
список игроков- просто люди которые онлайн или люди, на которых мжно нажать и начать игру, тогда зачем список игр(точнее не понятно как начать играть и чем простая игра от быстрой игры отличается)

**Comment by dcversus** [comment]
список игр:
логин игрока который создал \ игрок оппонент \ статус игры (ждет, играет, окончена) \ счет
В списке будет 15 последних игр.

**Comment by dcversus** [comment]
список игроков:
просто список людей онлайн, не кликабельный.

**Comment by olgakram** [comment]
ок

**Comment by dcversus** [comment]
клик по игре в списке игр (которые ожидают, т.е. нет второго игрока) - присоединиться
клик по кнопке игра \ быстрая игра просто создает игру и ты попадаешь в список ожидания

**Comment by dcversus** [comment]
в списке игроков еще нужно поле со статусом игрока (играет, ждет игры, или просто ждет)

**Comment by olgakram** [comment]
добавила комментарии к скетчам https://ninjamock.com/s/CQ65S. 
надеюсь завтра обсудим

**Comment by olgakram** [comment]
`экран загрузки`
![default](https://cloud.githubusercontent.com/assets/17432737/14476652/c488854c-0111-11e6-8163-de10c57a5393.png)

**Comment by olgakram** [comment]
> Экран авторизации

![default](https://cloud.githubusercontent.com/assets/17432737/14476677/ef2aa276-0111-11e6-8363-2dcaf0382960.png)

**Comment by olgakram** [comment]
![default](https://cloud.githubusercontent.com/assets/17432737/14476694/0a586984-0112-11e6-8942-2862899f96f3.png)

**Comment by olgakram** [comment]
![default](https://cloud.githubusercontent.com/assets/17432737/14476998/cee48c46-0113-11e6-9040-e664d9d0de4c.png)

**Comment by olgakram** [comment]
фишки должны соприкасаться друг с другом? или нет? 

![copy of](https://cloud.githubusercontent.com/assets/17432737/14477006/da244470-0113-11e6-8f1a-4a5038399cc6.png)

**Comment by dcversus** [comment]
Все нормально, кроме последнего... очень хаотично разбросаны фигуры. 

В идеале, ВСЕ поле заполнено шестиугольниками, контур фигур на которые можно ходить (вообще, все доступные для хода позиции) обведен четко, когда остальные фигуры еле заметны. Заполненные игроками фигуры целиком закрашены. 

Ждемс допила экрана и закрытия задачи.

**Comment by olgakram** [comment]
![default](https://cloud.githubusercontent.com/assets/17432737/14541007/77aef456-0290-11e6-95b6-876c2ffdcf54.png)

**Comment by olgakram** [comment]
![default](https://cloud.githubusercontent.com/assets/17432737/14541076/d802a442-0290-11e6-8bfd-356218d7a59e.png)

**Comment by olgakram** [comment]
лучше тут посмотреть https://ninjamock.com/s/CQ65S , выгружает картинку не полностью, теряет объекты((

**Comment by dcversus** [comment]
ох, пусть так...
