### ISSUE TITLE
фоновое изображение 

### ISSUE THREAD

**Issue by dcversus** [uz0/hexcraft#35]
Нужен бекграунд для главной страницы сайта. Светлая картинка в духе 
http://il9.picdn.net/shutterstock/videos/8809960/thumb/1.jpg?i10c=img.resize(height:160)
http://il6.picdn.net/shutterstock/videos/9162518/thumb/1.jpg?i10c=img.resize(height:160)

теги abstract, flare, water

**Comment by olgakram** [comment]
http://img12.nnm.me/4/6/d/2/3/f3c6090fcc6c746e370e86f1c08.jpg
http://boombob.ru/img/picture/Oct/15/84dd63546f821f31239a8163da9750fe/6.jpg
http://hd1366x768.ru/_ld/45/00236049.jpeg
http://otvoddetal.ru/b/3/svet_krugi_abstrakciya_tochki_abstraction_liniy_uzory_1920x1080.jpg
http://problex.ru/kartinki/3/colorfull_abstrakciya_digital_string_theory_2560x1440.jpg
http://storge.pic2.me/c/1360x800/931/5397e73b10d45.jpg
![-var-www-ord-data-www-gandex ru-upl-oboi-gandex ru-18509_6c5b560c2434be4f5fcca63f2f60e76d 1](https://cloud.githubusercontent.com/assets/17432737/14540303/0560bf4a-028d-11e6-9922-3bb774a89ac9.jpg)

**Comment by dcversus** [comment]
Все это на воду как-то совсем не похоже

**Comment by dcversus** [comment]
И нам нужно изображение с максимальным разрешением, не меньше 2k
