### ISSUE TITLE
Об игре

### ISSUE THREAD

**Issue by dcversus** [uz0/hexcraft#8]
Нужны тексты для страницы "об игре"
Примерная структура (нужно обсудить):
- Суть игры
- Правила игры
- ...
- ЧаВо

**Comment by danilstoyanov** [comment]
1)  Нужно определиться с размером игрового поля,  а также определиться с его внешним видом. Так как существует множество вариантов по форме и количеству клеток
2)  Необходимо выяснить, что может делать отдельная фигурка. Например гексагоне по ссылочке http://flesh.ru/flesh/game_13.html фигура имеет право либо сделать ход на соседнюю клетку, либо же, перепрыгнуть несколько клеток и «захватить фигуры соперника»
3)  Нужно продумать, сколько будет разновидностей фигурок. В гексагоне http://flesh.ru/flesh/game_13.html есть два вида шестиугольников: красные и белые кристаллы. В контексте Hexcraft, возможно есть смысл сделать 3 или 4разных видов кристаллов, которые бьются друг с другом.
4)  Нужно подумать о режимах игры (например сделать режим до победного конца, пока все фигурки противника не будут поглощены) или сделать режимы, которые ставят ограничение по времени (игра длится 3-4 минуты)

**Comment by dcversus** [comment]
1) размеры и конфигурация поля определяются картой.  У игры будет несколько заранее заготовленых карт.

2) фигура может занять соседнюю клетку или переместится через клетку (перепрыгнуть). Захват фигуры происходит при соприкосновении с соседней фигурой.

3) будет только один вид фигурок с разными цветами (определяется пользователем). На один бой два игрока.  Больше игроков на следующие версии.

4) режим игры один, на свободные клетки. Альтернативные режимы можно оставить на следующие версии.

Сейчас делаем боевой минимум, на этот минимум и ориентируем инструкцию. Остальные идеи собираем в какой нибудь задаче и потом раскидываем на следующие версии.

**Comment by danilstoyanov** [comment]
https://docs.google.com/document/d/1CBOyghWKSkZQFR-nk3KnKJyYTdrKuJAJMp9taZOA9BY/edit?usp=sharing

Вот ссылка, на документ с правилами, комментируем, бугуртим и обсуждаем!
