### ISSUE TITLE
Логотип

### ISSUE THREAD

**Issue by dcversus** [uz0/hexcraft#9]
- [x] предварительные варианты логотипа
- [x] выбор варианта для проработки
- [x] проработка
- [x] экспорт в svg

![image](https://cloud.githubusercontent.com/assets/8696354/14367952/766a94b4-fd23-11e5-8266-e34108e734aa.png)

выбранный логотип

**Comment by dcversus** [comment]
Будет использован:
главная страница (~1/6 от экрана)
типовая страница (новости, об игре) (~160px)
экран ожидания игры (~160px)

**Comment by dcversus** [comment]
![image](https://cloud.githubusercontent.com/assets/8696354/14142961/4dfad9a0-f691-11e5-84d5-f706d9f6ec80.png)

Изначальная версия логотипа. Возможно ориентируемся на этот образ. Или во всяком случае на "микробов". Тк это лучше вяжется с геймплеем.

**Comment by danilstoyanov** [comment]
![3](https://cloud.githubusercontent.com/assets/18240896/14231545/25f77916-f990-11e5-8d49-b2f03a970969.png)
Может быть, что-нибудь в таком духе?

**Comment by er-ant** [comment]
У Данила неплохая версия. Мне нравится

**Comment by karmagen** [comment]
Только тот что по середине может развернуть как и остальные?

**Comment by lisamgd** [comment]
Разве что спиной к нам

**Comment by dcversus** [comment]
Нужно минимум деталей. Чтобы можно было без проблем менять размер.

**Comment by TwoAbove** [comment]
Может что-то в таком духе? 
Понятно, что цвета другие, но общий смысл?
![hexcraft logo v1](https://cloud.githubusercontent.com/assets/9610438/14232951/3047a7a6-f9c2-11e5-8d43-c640d8bc1f7a.png)

**Comment by dcversus** [comment]
@TwoAbove нужно что-то более узнаваемое. Пиктограмма, образ который мы сможем гибко масштабировать, печатать итп. Нужна срисовка с первой картинке и в svg.

**Comment by lisamgd** [comment]
![11](https://cloud.githubusercontent.com/assets/18098651/14316893/dca25b94-fc48-11e5-86e2-8e95f13f1537.png)
![22](https://cloud.githubusercontent.com/assets/18098651/14316894/dca3c79a-fc48-11e5-9140-030e0e8a1de9.png)
![33](https://cloud.githubusercontent.com/assets/18098651/14316895/dcaab47e-fc48-11e5-973b-716f37c464c5.png)

**Comment by dcversus** [comment]
![image](https://cloud.githubusercontent.com/assets/8696354/14138990/f9a7ea72-f678-11e5-8189-ffabb5a106c4.png)

ориентируемся на этот вариант логотипа (в качестве истории)

**Comment by lisamgd** [comment]
![222](https://cloud.githubusercontent.com/assets/18098651/14387718/02078c28-fdee-11e5-8542-02dfa8ee5c4e.png)

**Comment by lisamgd** [comment]
![223](https://cloud.githubusercontent.com/assets/18098651/14402403/0d2c707a-fe78-11e5-8fa5-73109ab8326a.png)

**Comment by lisamgd** [comment]
![default](https://cloud.githubusercontent.com/assets/18098651/14409732/2ef19af4-ff5f-11e5-9f8e-838df91c037d.png)
